'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { LoginScreen } from '@/components/LoginScreen';
import { TemplateEditor } from '@/components/TemplateEditor';
import { getTemplates, saveTemplate, updateTemplate, deleteTemplate, Template, TemplateImage } from '@/lib/templates';
import { ArrowLeft, Plus, Edit2, Trash2, FileText } from 'lucide-react';

export default function TemplatesPage() {
  const router = useRouter();
    const [isLoggedIn, setIsLoggedIn] = useState(false);
      const [userLogin, setUserLogin] = useState('');
        const [templates, setTemplates] = useState<Template[]>([]);
          const [editingTemplate, setEditingTemplate] = useState<Template | null>(null);
            const [isCreating, setIsCreating] = useState(false);
              const [deleteConfirm, setDeleteConfirm] = useState<string | null>(null);
                const [loading, setLoading] = useState(false);

                  useEffect(() => {
                      const session = localStorage.getItem('doctorSession');
                          if (session) {
                                try {
                                        const parsed = JSON.parse(session);
                                                setIsLoggedIn(true);
                                                        setUserLogin(parsed.login ?? '');
                                                                loadTemplates(parsed.login ?? '');
                                                                      } catch (e) {
                                                                              console.error(e);
                                                                                    }
                                                                                        }
                                                                                          }, []);

                                                                                            const loadTemplates = async (login: string) => {
                                                                                                setLoading(true);
                                                                                                    try {
                                                                                                          const data = await getTemplates(login);
                                                                                                                setTemplates(data);
                                                                                                                    } catch (e) {
                                                                                                                          console.error(e);
                                                                                                                              } finally {
                                                                                                                                    setLoading(false);
                                                                                                                                        }
                                                                                                                                          };

                                                                                                                                            const refreshTemplates = () => loadTemplates(userLogin);

                                                                                                                                              const handleSaveOrUpdate = async (data: Partial<Template> & { name: string; headerText: string; content: string }) => {
                                                                                                                                                  if (editingTemplate && data.id) {
                                                                                                                                                        await updateTemplate(userLogin, { ...editingTemplate, ...data, images: (data.images ?? editingTemplate.images) as TemplateImage[] });
                                                                                                                                                            } else {
                                                                                                                                                                  await saveTemplate(userLogin, {
                                                                                                                                                                          name: data.name,
                                                                                                                                                                                  headerText: data.headerText,
                                                                                                                                                                                          content: data.content,
                                                                                                                                                                                                  images: (data.images ?? []) as TemplateImage[],
                                                                                                                                                                                                          isPublic: data.isPublic ?? false,
                                                                                                                                                                                                                  complaints: data.complaints ?? '',
                                                                                                                                                                                                                          anamnesis: data.anamnesis ?? '',
                                                                                                                                                                                                                                  diagnosis: data.diagnosis ?? '',
                                                                                                                                                                                                                                          treatment: data.treatment ?? '',
                                                                                                                                                                                                                                                  recommendations: data.recommendations ?? '',
                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                await refreshTemplates();
                                                                                                                                                                                                                                                                    setEditingTemplate(null);
                                                                                                                                                                                                                                                                        setIsCreating(false);
                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                            const handleDelete = async (id: string) => {
                                                                                                                                                                                                                                                                                await deleteTemplate(userLogin, id);
                                                                                                                                                                                                                                                                                    await refreshTemplates();
                                                                                                                                                                                                                                                                                        setDeleteConfirm(null);
                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                            if (!isLoggedIn) {
                                                                                                                                                                                                                                                                                                return <LoginScreen onLogin={(login, _name, _spec) => { setIsLoggedIn(true); setUserLogin(login); loadTemplates(login); }} />;
                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                    if (isCreating || editingTemplate) {
                                                                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                                                                              <TemplateEditor
                                                                                                                                                                                                                                                                                                                      template={editingTemplate ?? undefined}
                                                                                                                                                                                                                                                                                                                              onSave={handleSaveOrUpdate}
                                                                                                                                                                                                                                                                                                                                      onCancel={() => { setEditingTemplate(null); setIsCreating(false); }}
                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                                                                                                                        <div className="min-h-screen bg-gray-50">
                                                                                                                                                                                                                                                                                                                                                              <div className="max-w-4xl mx-auto p-4">
                                                                                                                                                                                                                                                                                                                                                                      <div className="flex items-center gap-3 mb-6">
                                                                                                                                                                                                                                                                                                                                                                                <button onClick={() => router.push('/')} className="p-2 hover:bg-gray-100 rounded-lg">
                                                                                                                                                                                                                                                                                                                                                                                            <ArrowLeft className="w-5 h-5" />
                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                <h1 className="text-2xl font-bold text-gray-800">Шаблоны</h1>
                                                                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                                                                      onClick={() => setIsCreating(true)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="ml-auto flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Plus className="w-4 h-4" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Создать шаблон
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {loading && <div className="text-center py-8 text-gray-500">Загрузка...</div>}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {!loading && templates.length === 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="text-center py-12 text-gray-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <FileText className="w-12 h-12 mx-auto mb-3 opacity-40" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p>Шаблонов пока нет. Создайте первый!</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="grid gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {templates.map(t => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div key={t.id} className="bg-white rounded-xl shadow-sm border p-4 flex items-start justify-between">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="flex-1 min-w-0">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="flex items-center gap-2 mb-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <FileText className="w-4 h-4 text-blue-500 flex-shrink-0" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h3 className="font-semibold text-gray-800 truncate">{t.name}</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {t.complaints && <p className="text-sm text-gray-500 truncate">Жалобы: {t.complaints}</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="flex items-center gap-2 ml-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={() => setEditingTemplate(t)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="p-2 hover:bg-gray-100 rounded-lg text-gray-600"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Edit2 className="w-4 h-4" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {deleteConfirm === t.id ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="flex items-center gap-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button onClick={() => handleDelete(t.id)} className="px-2 py-1 bg-red-500 text-white text-xs rounded">Удалить</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button onClick={() => setDeleteConfirm(null)} className="px-2 py-1 bg-gray-200 text-xs rounded">Отмена</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={() => setDeleteConfirm(t.id)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="p-2 hover:bg-gray-100 rounded-lg text-gray-600"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Trash2 className="w-4 h-4" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }